# -*- coding: utf-8 -*-
"""Proyecto_Ingeniería_Social.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GrwEvpXF0NXhMvbmwTbDpLbKfq9mZkJ3

**Proyecto Ingeniería Social**
"""

# Configurar permisos de Drive en Colab
from google.colab import drive
drive.mount('/content/drive')

# Importar las librerias
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Cargar datos
url = 'https://raw.githubusercontent.com/DanielMoondak/raul/main/encuesta_2024_para_poblacion_113.csv'
data = pd.read_csv(url, skiprows=[1])
data

# Seleccionar variables independientes (X) y dependiente (y)

# Independientes
X = data[['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'aa', 'ab']]

# Dependiente y variable objetivo
y = data['nivel']

# Dividir los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Entrenar el modelo de regresión logística
model = LogisticRegression()
model.fit(X_train, y_train)

# Realizar predicciones
y_pred = model.predict(X_test)

0# Calcula la precisión
accuracy = accuracy_score(y_test, y_pred)

# Calcula la matriz de confusión
conf_matrix = confusion_matrix(y_test, y_pred)

# Reporte de clasificación
class_report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(class_report)

# Función que solicita nuevos valores de características al usuario
def solicitar_nuevas_caracteristicas():
    # características a partir del formulario
    a = float(input("¿Cuál es tu género? 0-Hombre 1-Mujer: "))
    b = float(input("¿Cuál es su estado civil? 1.Soltero(a) 2.Casado(a) 3. Unión libre 4. Divorciado(a) 5. Viodo(a): "))
    c = float(input("¿Cuál es  su nivel actual de estudios? 1.Primaria 2.Secundaria 3.Bachillerato 4.Prepa 5.Licenciatura 6.Maestria 7.Doctorado: "))
    d = float(input("¿Alguna vez has recibido correos electrónicos o mensajes sospechosos solicitando información personal o credenciales de inicio de sesión?   (1=SI  0=NO): "))
    e = float(input("¿Has experimentado intentos de persuasión para revelar información confidencial a través de llamadas telefónicas o mensajes de texto?   (1=SI  0=NO): "))
    f = float(input("¿Te han invitado a hacer clic en enlaces desconocidos en correos electrónicos o mensajes de redes sociales?  (1=SI  0=NO): "))
    g = float(input("¿Has sido víctima de suplantación de identidad en línea o en redes sociales?    (1=SI  0=NO): "))
    h = float(input("¿Alguna vez has proporcionado información personal o financiera a través de sitios web que no parecían legítimos?   (1=SI  0=NO): "))
    i = float(input("¿Has presenciado casos en los que compañeros de clase o amigos han sido engañados por estafas en línea?   (1=SI  0=NO): "))
    j = float(input("¿Revisas la autenticidad de las fuentes antes de proporcionar información o interactuar en línea? (1=SI  0=NO): "))
    k = float(input("¿Has recibido mensajes de texto o correos electrónicos informándote que has ganado un premio o un sorteo en el que no recuerdas haber participado?  (1=SI  0=NO): "))
    l = float(input("¿Alguna vez has recibido correos electrónicos o mensajes sospechosos solicitando información personal o credenciales de inicio de sesión?  (1=SI  0=NO): "))
    m = float(input("¿Has sido testigo de casos en los que amigos o familiares han sido víctimas de fraudes en línea o estafas de phishing?  (1=SI  0=NO): "))
    n = float(input("¿Has recibido mensajes de redes sociales o WhatsApp de personas que no conoces solicitando información personal o financiera?  (1=SI  0=NO): "))
    o = float(input("¿Alguna vez has descargado archivos adjuntos o software de fuentes no confiables en correos electrónicos o mensajes en línea?  (1=SI  0=NO): "))
    p = float(input("¿Has compartido información personal o confidencial en foros en línea, grupos de redes sociales o plataformas de mensajería?  (1=SI 0=NO): "))
    q = float(input("¿Has sido víctima de acoso o ciberbullying en línea?  (1=SI 0=NO): "))
    r = float(input("¿Has experimentado intentos de acceso no autorizado a tus cuentas en línea, como intentos de inicio de sesión con contraseñas incorrectas?  (1=SI 0=NO): "))
    s = float(input("¿Has participado en actividades de capacitación o talleres sobre seguridad en línea en el pasado?  (1=SI 0=NO): "))
    t = float(input("¿Has recibido mensajes de redes sociales o correos electrónicos que parecían provenir de amigos o contactos, pero que en realidad fueron enviados por suplantadores?  (1=SI 0=NO): "))
    u = float(input("¿Has proporcionado información personal o financiera en respuesta a llamadas telefónicas no solicitadas o mensajes de texto de remitentes desconocidos? (1=SI 0=NO): "))
    v = float(input("¿Has recibido llamadas telefónicas de personas que afirmaban ser representantes de instituciones financieras o gubernamentales solicitando información confidencial?  (1=SI 0=NO): "))
    w = float(input("¿Has utilizado redes Wi-Fi públicas para acceder a información personal o financiera, como cuentas bancarias o correos electrónicos?  (1=SI 0=NO): "))
    x = float(input("¿Has sido testigo de casos en los que compañeros de clase o amigos han compartido información confidencial en línea de manera imprudente?  (1=SI 0=NO): "))
    y = float(input("¿Has descargado aplicaciones móviles de fuentes no oficiales o desconocidas?  (1=SI 0=NO): "))
    z = float(input("¿Has sido víctima de intentos de extorsión en línea, como el chantaje con información personal comprometedora?  (1=SI 0=NO): "))
    aa = float(input("¿Alguna vez has sido redirigido a sitios web falsos o de phishing que intentaban imitar sitios web legítimos?  (1=SI 0=NO): "))
    ab = float(input("¿Has sido blanco de intentos de extorsión en línea, como amenazas de revelar información personal o íntima si no pagas un rescate? (1=SI 0=NO): "))

    # Crear un DataFrame con los nuevos valores de características
    nuevas_caracteristicas = pd.DataFrame({
        'a': [a],
        'b': [b],
        'c': [c],
        'd': [d],
        'e': [e],
        'f': [f],
        'g': [g],
        'h': [h],
        'i': [i],
        'j': [j],
        'k': [k],
        'l': [l],
        'm': [m],
        'n': [n],
        'o': [o],
        'p': [p],
        'q': [q],
        'r': [r],
        's': [s],
        't': [t],
        'u': [u],
        'v': [v],
        'w': [w],
        'x': [x],
        'y': [y],
        'z': [z],
        'aa': [aa],
        'ab': [ab]
    })

    return nuevas_caracteristicas

# Predecir el nuevo target usando las características proporcionadas por el usuario
nuevas_caracteristicas = solicitar_nuevas_caracteristicas()
nueva_prediccion = model.predict(nuevas_caracteristicas)

print(f"Tu nivel de vulnerabilidad ante técnicas de Ingeniería Social es:  {nueva_prediccion[0]}")

